In [12]:
!pip install geopandas==0.12.1;
!pip install rtree;
!pip install pyarrow==10.0.0 s3fs folium

Collecting geopandas==0.12.1
  Downloading geopandas-0.12.1-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 18.6 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: fiona>=1.8 in /opt/mamba/lib/python3.10/site-packages (from geopandas==0.12.1) (1.8.22)
Requirement already satisfied: pyproj>=2.6.1.post1 in /opt/mamba/lib/python3.10/site-packages (from geopandas==0.12.1) (3.4.0)
Requirement already satisfied: packaging in /opt/mamba/lib/python3.10/site-packages (from geopandas==0.12.1) (21.3)
Requirement already satisfied: shapely>=1.7 in /opt/mamba/lib/python3.10/site-packages (from geopandas==0.12.1) (1.8.5)
Requirement already satisfied: pandas>=1.0.0 in /opt/mamba/lib/python3.10/site-packages (from geopandas==0.12.1) (1.5.1)
Requirement already satisfied: six>=1.7 in /opt/mamba/lib/python3.10/site-packages (from fiona>=1.8->geopandas==0.12.1) (1.16.0)
Requirement already satisfied: click>=4.0 in /opt/mamba/lib/python3.10/site-packages (from fiona>=1.8->geopandas==0.12.1) (8.1.3)
Requirement already satisfied: cligj>=0.5 in /opt/mamba/lib/python3.10/site-packages (from fiona>=1.8->geopandas==0.12.1) (0.7.2)
Requirement already satisfied: certifi in /opt/mamba/lib/python3.10/site-packages (from fiona>=1.8->geopandas==0.12.1) (2022.9.24)
Requirement already satisfied: setuptools in /opt/mamba/lib/python3.10/site-packages (from fiona>=1.8->geopandas==0.12.1) (65.5.0)
Requirement already satisfied: click-plugins>=1.0 in /opt/mamba/lib/python3.10/site-packages (from fiona>=1.8->geopandas==0.12.1) (1.1.1)
Requirement already satisfied: munch in /opt/mamba/lib/python3.10/site-packages (from fiona>=1.8->geopandas==0.12.1) (2.5.0)
Requirement already satisfied: attrs>=17 in /opt/mamba/lib/python3.10/site-packages (from fiona>=1.8->geopandas==0.12.1) (22.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/mamba/lib/python3.10/site-packages (from pandas>=1.0.0->geopandas==0.12.1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/mamba/lib/python3.10/site-packages (from pandas>=1.0.0->geopandas==0.12.1) (2022.5)
Requirement already satisfied: numpy>=1.21.0 in /opt/mamba/lib/python3.10/site-packages (from pandas>=1.0.0->geopandas==0.12.1) (1.23.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/mamba/lib/python3.10/site-packages (from packaging->geopandas==0.12.1) (3.0.9)
Installing collected packages: geopandas
  Attempting uninstall: geopandas
    Found existing installation: geopandas 0.12.0
    Uninstalling geopandas-0.12.0:
      Successfully uninstalled geopandas-0.12.0
Successfully installed geopandas-0.12.1
Requirement already satisfied: rtree in /opt/mamba/lib/python3.10/site-packages (1.0.1)
Collecting pyarrow==10.0.0
  Downloading pyarrow-10.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 14.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: s3fs in /opt/mamba/lib/python3.10/site-packages (0.4.2)
Requirement already satisfied: folium in /opt/mamba/lib/python3.10/site-packages (0.13.0)
Requirement already satisfied: numpy>=1.16.6 in /opt/mamba/lib/python3.10/site-packages (from pyarrow==10.0.0) (1.23.4)
Requirement already satisfied: fsspec>=0.6.0 in /opt/mamba/lib/python3.10/site-packages (from s3fs) (2022.10.0)
Requirement already satisfied: botocore>=1.12.91 in /opt/mamba/lib/python3.10/site-packages (from s3fs) (1.28.2)
Requirement already satisfied: jinja2>=2.9 in /opt/mamba/lib/python3.10/site-packages (from folium) (3.1.2)
Requirement already satisfied: requests in /opt/mamba/lib/python3.10/site-packages (from folium) (2.28.1)
Requirement already satisfied: branca>=0.3.0 in /opt/mamba/lib/python3.10/site-packages (from folium) (0.5.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/mamba/lib/python3.10/site-packages (from botocore>=1.12.91->s3fs) (2.8.2)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/mamba/lib/python3.10/site-packages (from botocore>=1.12.91->s3fs) (1.0.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/mamba/lib/python3.10/site-packages (from botocore>=1.12.91->s3fs) (1.26.11)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/mamba/lib/python3.10/site-packages (from jinja2>=2.9->folium) (2.1.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/mamba/lib/python3.10/site-packages (from requests->folium) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/mamba/lib/python3.10/site-packages (from requests->folium) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /opt/mamba/lib/python3.10/site-packages (from requests->folium) (3.4)
Requirement already satisfied: six>=1.5 in /opt/mamba/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.12.91->s3fs) (1.16.0)
Installing collected packages: pyarrow
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 9.0.0
    Uninstalling pyarrow-9.0.0:
      Successfully uninstalled pyarrow-9.0.0
Successfully installed pyarrow-10.0.0

In [1]:
import os
os.getcwd()

'/home/onyxia/work/hackathon-un-2022/notebooks'

In [2]:
os.chdir("..")
import utils.functions as fc

In [3]:
from importlib import reload
fc = reload(fc)

In [4]:
ship_data_enriched = fc.create_ship_data_enriched()

In [5]:
path_parquet = "AIS/ais_azov_black_20220401_20220408_full_traces.parquet"

ais_df = fc.read_ais_parquet(path_parquet=path_parquet)

In [13]:
import pandas as pd

pd.options.display.max_columns = 30
ais_df.head()

        mmsi   latitude  longitude  eeid       dt_insert_utc destination
0  249637000  44.305513  30.317422   NaN 2019-03-25 08:34:45      BILBAO
1  511942000  44.208553  30.109788   NaN 2019-03-25 04:05:53     KHERSON
2  511942000  44.327867  30.157003   NaN 2019-03-25 05:02:12     KHERSON
3  511942000  44.324473  30.155405   NaN 2019-03-25 05:00:33     KHERSON
4  235105944  40.978187  29.039550   NaN 2019-03-25 03:41:31        None

In [40]:
ais_df["lat2"] = ais_df["latitude"] - 1
ais_df["long2"] = ais_df["longitude"] + 1
ais_df

,mmsi,latitude,longitude,eeid,dt_insert_utc,destination,coordinates,lat2,long2
0,249637000,44.305513,30.317422,NaN,2019-03-25 08:34:45,BILBAO,POINT (30.31742 44.30551),43.305513,31.317422
1,511942000,44.208553,30.109788,NaN,2019-03-25 04:05:53,KHERSON,POINT (30.10979 44.20855),43.208553,31.109788
2,511942000,44.327867,30.157003,NaN,2019-03-25 05:02:12,KHERSON,POINT (30.15700 44.32787),43.327867,31.157003
3,511942000,44.324473,30.155405,NaN,2019-03-25 05:00:33,KHERSON,POINT (30.15540 44.32447),43.324473,31.155405
4,235105944,40.978187,29.039550,NaN,2019-03-25 03:41:31,None,POINT (29.03955 40.97819),39.978187,30.039550
...,...,...,...,...,...,...,...,...,...
4406585,229407000,26.090000,-80.121667,NaN,2019-03-28 06:21:27,PORT EVERGLADES,POINT (-80.12167 26.09000),25.090000,-79.121667
4406586,229407000,26.090000,-80.121667,NaN,2019-03-28 11:45:28,PORT EVERGLADES,POINT (-80.12167 26.09000),25.090000,-79.121667
4406587,229407000,26.090000,-80.121667,NaN,2019-03-28 00:03:28,PORT EVERGLADES,POINT (-80.12167 26.09000),25.090000,-79.121667
4406588,229407000,26.090000,-80.121667,NaN,2019-03-28 00:27:28,PORT EVERGLADES,POINT (-80.12167 26.09000),25.090000,-79.121667
4406589,229407000,26.090000,-80.121667,NaN,2019-03-28 00:12:28,PORT EVERGLADES,POINT (-80.12167 26.09000),25.090000,-79.121667

In [ ]:
ais_df.map()

In [41]:
!pip install geopy

Collecting geopy
  Downloading geopy-2.2.0-py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.9/118.9 kB 4.1 MB/s eta 0:00:00
Collecting geographiclib<2,>=1.49
  Downloading geographiclib-1.52-py3-none-any.whl (38 kB)
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-1.52 geopy-2.2.0

In [44]:
!pip install h3
import h3

Collecting h3
  Downloading h3-3.7.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 14.0 MB/s eta 0:00:0000:0100:01
Installing collected packages: h3
Successfully installed h3-3.7.4

In [ ]:
!pip install h3
import h3
df['distance'] = df.apply(lambda row: h3.point_dist((row['lat1'], row['long1']), (row['lat2'], row['long2'])), axis=1)